name: drain_eye
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

repository: https://github.com/moevm/mse1h2026-draineye
issue_tracker: https://github.com/moevm/mse1h2026-draineye/issues

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
